import { Cardinality } from "../data/constants";

export const template7 = {
  tables: [
    {
      id: 0,
      name: "patients",
      x: 300,
      y: 20,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "first_name",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
          size: 255,
        },
        {
          name: "last_name",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
          size: 255,
        },
        {
          name: "gender",
          type: "ENUM",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
          values: ["Male", "Female", "Other"],
        },
        {
          name: "dob",
          type: "DATE",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 4,
        },
        {
          name: "phone",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 5,
          size: 20,
        },
        {
          name: "email",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 6,
          size: 255,
        },
        {
          name: "address",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 7,
          size: 255,
        },
        {
          name: "blood_group",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 8,
          size: 5,
        },
        {
          name: "emergency_contact",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 9,
          size: 255,
        },
        {
          name: "created_at",
          type: "TIMESTAMP",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 10,
        },
      ],
      comment: "",
      indices: [],
      color: "#175e7a",
    },
    {
      id: 1,
      name: "doctors",
      x: 650,
      y: 20,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "first_name",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
          size: 255,
        },
        {
          name: "last_name",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
          size: 255,
        },
        {
          name: "specialization",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
          size: 255,
        },
        {
          name: "department_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 4,
        },
        {
          name: "phone",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 5,
          size: 20,
        },
        {
          name: "email",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 6,
          size: 255,
        },
        {
          name: "experience_years",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 7,
        },
      ],
      comment: "",
      indices: [],
      color: "#6360f7",
    },
    {
      id: 2,
      name: "departments",
      x: 1000,
      y: 20,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "name",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
          size: 255,
        },
        {
          name: "description",
          type: "TEXT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
        },
        {
          name: "head_doctor_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
        },
      ],
      comment: "",
      indices: [],
      color: "#3cde7d",
    },
    {
      id: 3,
      name: "appointments",
      x: 300,
      y: 500,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "patient_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
        },
        {
          name: "doctor_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
        },
        {
          name: "appointment_date",
          type: "DATE",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
        },
        {
          name: "appointment_time",
          type: "TIME",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 4,
        },
        {
          name: "status",
          type: "ENUM",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 5,
          values: ["Scheduled", "Completed", "Cancelled"],
        },
        {
          name: "notes",
          type: "TEXT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 6,
        },
      ],
      comment: "",
      indices: [],
      color: "#f5a623",
    },
    {
      id: 4,
      name: "medical_records",
      x: 650,
      y: 500,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "patient_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
        },
        {
          name: "doctor_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
        },
        {
          name: "diagnosis",
          type: "TEXT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
        },
        {
          name: "treatment",
          type: "TEXT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 4,
        },
        {
          name: "prescription",
          type: "TEXT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 5,
        },
        {
          name: "visit_date",
          type: "DATE",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 6,
        },
      ],
      comment: "",
      indices: [],
      color: "#d0021b",
    },
    {
      id: 5,
      name: "rooms",
      x: 1000,
      y: 900,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "room_number",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
          size: 50,
        },
        {
          name: "room_type",
          type: "ENUM",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
          values: ["General", "ICU", "Private", "Emergency"],
        },
        {
          name: "status",
          type: "ENUM",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
          values: ["Available", "Occupied", "Maintenance"],
        },
      ],
      comment: "",
      indices: [],
      color: "#8b572a",
    },
    {
      id: 6,
      name: "admissions",
      x: 650,
      y: 900,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "patient_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
        },
        {
          name: "room_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
        },
        {
          name: "admitted_date",
          type: "DATETIME",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
        },
        {
          name: "discharged_date",
          type: "DATETIME",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 4,
        },
        {
          name: "reason",
          type: "TEXT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 5,
        },
      ],
      comment: "",
      indices: [],
      color: "#4a90e2",
    },
    {
      id: 7,
      name: "billing",
      x: 300,
      y: 900,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "patient_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
        },
        {
          name: "appointment_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
        },
        {
          name: "admission_id",
          type: "INT",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
        },
        {
          name: "total_amount",
          type: "DOUBLE",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 4,
        },
        {
          name: "status",
          type: "ENUM",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 5,
          values: ["Paid", "Pending", "Cancelled"],
        },
        {
          name: "payment_date",
          type: "DATETIME",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 6,
        },
      ],
      comment: "",
      indices: [],
      color: "#bd10e0",
    },
    {
      id: 8,
      name: "users",
      x: 20,
      y: 20,
      fields: [
        {
          name: "id",
          type: "INT",
          default: "",
          check: "",
          primary: true,
          unique: true,
          notNull: true,
          increment: true,
          comment: "",
          id: 0,
        },
        {
          name: "username",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 1,
          size: 255,
        },
        {
          name: "password",
          type: "VARCHAR",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 2,
          size: 255,
        },
        {
          name: "role",
          type: "ENUM",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 3,
          values: ["Admin", "Doctor", "Receptionist"],
        },
        {
          name: "last_login",
          type: "TIMESTAMP",
          default: "",
          check: "",
          primary: false,
          unique: false,
          notNull: false,
          increment: false,
          comment: "",
          id: 4,
        },
      ],
      comment: "",
      indices: [],
      color: "#9013fe",
    },
  ],
  relationships: [
    {
      startTableId: 0,
      startFieldId: 0,
      endTableId: 3,
      endFieldId: 1,
      name: "appointments_patient_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 0,
    },
    {
      startTableId: 1,
      startFieldId: 0,
      endTableId: 3,
      endFieldId: 2,
      name: "appointments_doctor_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 1,
    },
    {
      startTableId: 0,
      startFieldId: 0,
      endTableId: 4,
      endFieldId: 1,
      name: "medical_records_patient_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 2,
    },
    {
      startTableId: 1,
      startFieldId: 0,
      endTableId: 4,
      endFieldId: 2,
      name: "medical_records_doctor_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 3,
    },
    {
      startTableId: 2,
      startFieldId: 0,
      endTableId: 1,
      endFieldId: 4,
      name: "doctors_department_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 4,
    },
    {
      startTableId: 0,
      startFieldId: 0,
      endTableId: 6,
      endFieldId: 1,
      name: "admissions_patient_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 5,
    },
    {
      startTableId: 5,
      startFieldId: 0,
      endTableId: 6,
      endFieldId: 2,
      name: "admissions_room_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 6,
    },
    {
      startTableId: 0,
      startFieldId: 0,
      endTableId: 7,
      endFieldId: 1,
      name: "billing_patient_id_fk",
      cardinality: Cardinality.ONE_TO_MANY,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 7,
    },
    {
      startTableId: 3,
      startFieldId: 0,
      endTableId: 7,
      endFieldId: 2,
      name: "billing_appointment_id_fk",
      cardinality: Cardinality.ONE_TO_ONE,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 8,
    },
    {
      startTableId: 6,
      startFieldId: 0,
      endTableId: 7,
      endFieldId: 3,
      name: "billing_admission_id_fk",
      cardinality: Cardinality.ONE_TO_ONE,
      updateConstraint: "No action",
      deleteConstraint: "No action",
      id: 9,
    },
  ],
  notes: [],
  subjectAreas: [],
  types: [],
  title: "Healthcare Management schema",
  description:
    "A comprehensive Healthcare Management ER diagram template including patients, doctors, appointments, medical records, billing, and more.",
  custom: 0,
};
