const menu = {
  File: {
    New: [],
    "New window": [],
    Save: [],
    "Save as": [],
    Share: [],
    Rename: [],
    Import: [],
    "Export as": [".png", ".jpg", ".pdf", ".xml"],
    "Export source": ["MySQL", "PostgreSQL", "DBML"],
    Properties: [],
    Close: [],
  },
  Edit: {
    Undo: [],
    Redo: [],
    Cut: [],
    Copy: [],
    "Copy as image": [],
    Paste: [],
    Delete: [],
    "Edit table": [],
  },
  View: {
    Toolbar: [],
    Grid: [],
    Sidebar: [],
    Editor: [],
    "Reset view": [],
    "View schema": [],
    Theme: ["Light", "Dark"],
    "Zoom in": [],
    "Zoom out": [],
    Fullscreen: [],
  },
  Insert: {
    "New table": [],
    "New relationship": [],
    Note: [],
    Image: [],
    Textbox: [],
    Shape: ["Rhombus", "Rectangle"],
  },
  Logs: {
    "Open logs": [],
    "Commit changes": [],
    "Revert changes": [],
    "View commits": [],
  },
  Help: {
    Shortcuts: [],
    "Ask us on discord": [],
    "Tweet us": [],
    "Found a bug": [],
  },
};

export default menu;
