import { appendViews } from "../views";
import {
  escapeQuotes,
  exportFieldComment,
  parseDefault,
  uniqueConstraintClause,
  getFkColumnNames,
} from "./shared";
import { dbToTypes } from "../../data/datatypes";

function tablesToPostgres(diagram) {
  const enumStatements = diagram.enums
    .map(
      (e) =>
        `CREATE TYPE "${e.name}" AS ENUM (\n${e.values
          .map((v) => `\t'${escapeQuotes(String(v))}'`)
          .join(",\n")}\n);\n`,
    )
    .join("\n");

  const typeStatements = diagram.types
    .map(
      (type) =>
        `CREATE TYPE ${type.name} AS (\n${type.fields
          .map((f) => `\t${f.name} ${f.type}`)
          .join(",\n")}\n);${
          type.comment?.trim()
            ? `\n\nCOMMENT ON TYPE "${type.name}" IS '${escapeQuotes(type.comment)}';`
            : ""
        }`,
    )
    .join("\n\n");

  const tableStatements = diagram.tables
    .map((table) => {
      const inheritsClause =
        Array.isArray(table.inherits) && table.inherits.length > 0
          ? `\n) INHERITS (${table.inherits.map((parent) => `"${parent}"`).join(", ")})`
          : "\n)";

      const fieldDefinitions = table.fields
        .map(
          (field) =>
            `${exportFieldComment(field.comment)}\t"${
              field.name
            }" ${field.type}${
              field.size ? `(${field.size})` : ""
            }${field.isArray ? " ARRAY" : ""}${field.notNull ? " NOT NULL" : ""}${
              field.unique ? " UNIQUE" : ""
            }${field.increment ? " GENERATED BY DEFAULT AS IDENTITY" : ""}${
              String(field.default ?? "").trim()
                ? ` DEFAULT ${parseDefault(field, diagram.database)}`
                : ""
            }${
              field.check && dbToTypes[diagram.database][field.type]?.hasCheck
                ? ` CHECK(${field.check})`
                : ""
            }`,
        )
        .join(",\n");

      const primaryKeyClause = table.fields.some((f) => f.primary)
        ? `,\n\tPRIMARY KEY(${table.fields
            .filter((f) => f.primary)
            .map((f) => `"${f.name}"`)
            .join(", ")})`
        : "";

      const uniqueClause = uniqueConstraintClause(table, (s) => `"${s}"`);

      const commentStatements = [
        table.comment?.trim()
          ? `COMMENT ON TABLE "${table.name}" IS '${escapeQuotes(table.comment)}';`
          : "",
        ...table.fields.map((field) =>
          field.comment?.trim()
            ? `COMMENT ON COLUMN "${table.name}"."${field.name}" IS '${escapeQuotes(field.comment)}';`
            : "",
        ),
      ]
        .filter(Boolean)
        .join("\n");

      const indexStatements = table.indices
        .map(
          (i) =>
            `CREATE ${i.unique ? "UNIQUE " : ""}INDEX "${i.name}"\nON "${table.name}" (${i.fields
              .map((f) => `"${f}"`)
              .join(", ")});`,
        )
        .join("\n");

      return [
        `CREATE TABLE IF NOT EXISTS "${table.name}" (\n${fieldDefinitions}${primaryKeyClause}${uniqueClause}${inheritsClause};`,
        commentStatements,
        indexStatements,
      ]
        .filter(Boolean)
        .join("\n\n");
    })
    .join("\n\n");

  const foreignKeyStatements = diagram.references
    .map((r) => {
      const startTable = diagram.tables.find((t) => t.id === r.startTableId);
      const endTable = diagram.tables.find((t) => t.id === r.endTableId);

      if (!startTable || !endTable) return "";

      const { startColumns, endColumns } = getFkColumnNames(
        r,
        startTable,
        endTable,
      );
      if (startColumns.some((c) => !c) || endColumns.some((c) => !c))
        return "";

      return `ALTER TABLE "${startTable.name}"\nADD FOREIGN KEY(${startColumns
        .map((c) => `"${c}"`)
        .join(", ")}) REFERENCES "${endTable.name}"(${endColumns
        .map((c) => `"${c}"`)
        .join(", ")})\nON UPDATE ${r.updateConstraint.toUpperCase()} ON DELETE ${r.deleteConstraint.toUpperCase()};`;
    })
    .filter(Boolean)
    .join("\n");

  return [
    enumStatements,
    typeStatements,
    tableStatements,
    foreignKeyStatements,
  ]
    .map((s) => s.trim())
    .filter(Boolean)
    .join("\n\n");
}

export function toPostgres(diagram) {
  return appendViews(tablesToPostgres(diagram), diagram);
}
